 ###
 GET http://localhost:9000/
 
###
#GET http://localhost:9000/traffic-light
###
GET http://localhost:9000/traffic-light-DB
###
#GET http://localhost:9000/traffic-light/2
###
GET http://localhost:9000/traffic-light-DB/24
###
#PUT http://localhost:9000/traffic-light
#content-type: application/json
#
#{
#    "id" : 1,
#    "color" : "Red"
#}

###
PUT http://localhost:9000/traffic-light-DB
content-type: application/json

{
  "id" : 1,
  "color" : "Red"
}

###
PUT http://localhost:9000/traffic-light-DB
content-type: application/json

{
  "id" : 30,
  "color" : "Green"
}

###
#PUT http://localhost:9001/traffic-light
#Content-Type: application/json
#
#{
#  "id": 12,
#  "color": "Green"
#}
####
#PUT http://localhost:9000/traffic-light-async
#Content-Type: application/json
#
#{
#  "id": 12,
#  "color": "Red"
#}
###
 GET http://localhost:9000/avail

###
GET http://localhost:9000/traffic-light?color=Green