 ###
  GET http://localhost:9000/traffic-light
###

GET http://localhost:9000/traffic-light/3

###
PUT http://localhost:9000/traffic-light 
content-type:  application/json

{
    "id" : 26,
    "color" : "Orange"
}

###
